services:
  dpanel:
    image: dpanel/dpanel:lite
    ports:
      - 0:8080 # 替换 8807 可更改面板访问端口
    # environment:
    #   APP_NAME: dpanel # 请保持此名称与 container_name 一致
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./dpanel:/dpanel # 将 /home/dpanel 更改为你想要挂载的宿主机目录
      # - ./dpanel/dpanel.db:/dpanel/dpanel.db
    restart: unless-stopped
    networks:
      - software-network

  portainer-agent:
    image: portainer/agent
    ports:
      - 9001:9001
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
    networks:
      - software-network

networks:
  software-network:
    external: true
