# services:
#   node-latest:
#     image: node:latest
#     working_dir: /usr/src/app
#     volumes:
#       - ./node-created:/usr/src/app
#     command: npx hexo init new-hexo-app # 自动安装依赖并启动
#   node-20:
#     image: node:20-alpine
#     working_dir: /usr/src/app
#     ports:
#       - "30001:3000"
#     volumes:
#       - ./node-20:/usr/src/app
#       - /use/src/app/node_modules
#     environment:
#       - NODE_ENV=development
#     command: sh -c "npm init -y && node index.js" # 自动安装依赖并启动
#   php-latest:
#   php-56:
#   composer-latest:
#     image: composer:latest
#     working_dir: /usr/src/app
#     volumes:
#       - ./composer-created:/usr/src/app
#     command: composer init --name docker/composer-create --author docker --stability alpha --license MIT
#     # command: composer create-project --prefer-dist laravel/laravel ./laravel5 5.5.
# networks:
#   software-network:
#     external: true
