<?php

use phpspider\core\phpspider;

return [
  "default"               => [
    'slug'                => 'magnet_',
    'name'                => '🔴🟡🟢【磁力】',
    'title'               => "🔴🟡🟢【磁力】",
    'log_show'            => true,
    'log_file'            => 'logs/magnet_.log',
    'log_type'            => 'info,debug,success,warn,error',
    'log_debug'           => true,
    'cache_path'          => 'cache/magnet_',
    'max_depth'           => 0,
    'max_fields'          => 0,
    'export_type'         => 'db',
    'export_table'        => 'magnet_contents',
    'domains'             => [],
    'scan_urls'           => [],
    'list_url_regexes'    => [],
    'content_url_regexes' => [],
    "fields" => [
      "id"                => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => '',                   'filter' => '', "default" => "",  'data_type' => "int", 'nullable' => false, "data_default" => "", "primary_key" => true, "auto_increment" => true],
      "collect_slug"      => ['required' => true,  'repeated' => false, 'name' => "collect_slug",   'selector' => "",              'prop' => 'config.slug',        'filter' => '',  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "collect_status"  => ['required' => false, 'repeated' => false, 'name' => "collect_status",  'selector' => "",              'prop' => '',                   'filter' => '',],
      // "collect_type"   => ['required' => false, 'repeated' => false, 'name' => "collect_type",   'selector' => "",              'prop' => 'page.link.url_type', 'filter' => '',],
      "url"               => ['required' => false, 'repeated' => false, 'name' => "url",            'selector' => "",              'prop' => 'page.url',           'filter' => '', 'data_type' => "varchar(255)", 'nullable' => false,  "data_index" => true,],
      // "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', "default" => "",  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "url_md5"        => ['required' => true,  'repeated' => false, 'name' => "url_md5",        'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', 'data_type' => "varchar(32)", 'nullable' => false,  "data_index" => true,],
      "collect_at"        => ['required' => false, 'repeated' => false, 'name' => "collect_at",     'selector' => "",              'prop' => 'current_timestamp',               'filter' => '', 'data_type' => "varchar(10)",],

      "category"          => ['required' => false, 'repeated' => false, 'name' => "category",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "title"             => ['required' => true,  'repeated' => false, 'name' => "title",          'selector' => "//html//title", 'prop' => '',                   'filter' => '',],
      "description"       => ['required' => false, 'repeated' => false, 'name' => "description",    'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],
      "keywords"          => ['required' => false, 'repeated' => false, 'name' => "keywords",       'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],

      "slug"              => ['required' => false, 'repeated' => false, 'name' => "slug",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "ico"               => ['required' => false, 'repeated' => false, 'name' => "ico",            'selector' => "",              'prop' => '',                   'filter' => '',],

      "text"              => ['required' => false, 'repeated' => false, 'name' => "text",           'selector' => "",              'prop' => '',                   'filter' => '',],

      "option_a"          => ['required' => false, 'repeated' => false, 'name' => "option_a",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_b"          => ['required' => false, 'repeated' => false, 'name' => "option_b",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_c"          => ['required' => false, 'repeated' => false, 'name' => "option_c",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_d"          => ['required' => false, 'repeated' => false, 'name' => "option_d",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_e"          => ['required' => false, 'repeated' => false, 'name' => "option_e",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_f"          => ['required' => false, 'repeated' => false, 'name' => "option_f",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_g"          => ['required' => false, 'repeated' => false, 'name' => "option_g",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "type"              => ['required' => false, 'repeated' => false, 'name' => "type",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "status"            => ['required' => false, 'repeated' => false, 'name' => "status",         'selector' => "",              'prop' => '',                   'filter' => '',],

      "answer"            => ['required' => false, 'repeated' => false, 'name' => "answer",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "analysis"          => ['required' => false, 'repeated' => false, 'name' => "analysis",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "parent"            => ['required' => false, 'repeated' => false, 'name' => "parent",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "count"             => ['required' => false, 'repeated' => false, 'name' => "count",          'selector' => "",              'prop' => '',                   'filter' => '',],
      "order"             => ['required' => false, 'repeated' => false, 'name' => "order",          'selector' => "",              'prop' => '',                   'filter' => '',],

      "created_at"        => ['required' => false, 'repeated' => false, 'name' => "created_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "updated_at"        => ['required' => false, 'repeated' => false, 'name' => "updated_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "release_at"        => ['required' => false, 'repeated' => false, 'name' => "release_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "deleted_at"        => ['required' => false, 'repeated' => false, 'name' => "deleted_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "cilimao"               => [
    'slug'                => 'magnet_cilimao',
    'name'                => '🔴【磁力】磁力猫',
    'title'               => "🔴【磁力】磁力猫",
    'log_show'            => true,
    'log_file'            => 'logs/magnet_cilimao.log',
    'log_type'            => 'info,debug,success,warn,error',
    'log_debug'           => true,
    'cache_path'          => 'cache/magnet_',
    'max_depth'           => 0,
    'max_fields'          => 0,
    'export_type'         => 'db',
    'export_table'        => 'magnet_contents',
    'domains'             => ['clm42.top'],
    'scan_urls'           => ['https://clm42.top/', 'https://clm42.top/search?word=5rW054Gr5LmL6Lev&sort=time'],
    'list_url_regexes'    => ['https://clm42.top/search?word=\s+'],
    'content_url_regexes' => ['https://clm42.top/information/\s+'],
    "fields" => [
      "id"                => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => '',                   'filter' => '', "default" => "",  'data_type' => "int", 'nullable' => false, "data_default" => "", "primary_key" => true, "auto_increment" => true],
      "collect_slug"      => ['required' => true,  'repeated' => false, 'name' => "collect_slug",   'selector' => "",              'prop' => 'config.slug',        'filter' => '',  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "collect_status"  => ['required' => false, 'repeated' => false, 'name' => "collect_status",  'selector' => "",              'prop' => '',                   'filter' => '',],
      // "collect_type"   => ['required' => false, 'repeated' => false, 'name' => "collect_type",   'selector' => "",              'prop' => 'page.link.url_type', 'filter' => '',],
      "url"               => ['required' => false, 'repeated' => false, 'name' => "url",            'selector' => "",              'prop' => 'page.url',           'filter' => '', 'data_type' => "varchar(255)", 'nullable' => false,  "data_index" => true,],
      // "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', "default" => "",  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "url_md5"        => ['required' => true,  'repeated' => false, 'name' => "url_md5",        'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', 'data_type' => "varchar(32)", 'nullable' => false,  "data_index" => true,],
      "collect_at"        => ['required' => false, 'repeated' => false, 'name' => "collect_at",     'selector' => "",              'prop' => 'current_timestamp',               'filter' => '', 'data_type' => "varchar(10)",],

      "category"          => ['required' => false, 'repeated' => false, 'name' => "category",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "title"             => ['required' => true,  'repeated' => false, 'name' => "title",          'selector' => "//html//title", 'prop' => '',                   'filter' => '',],
      "description"       => ['required' => false, 'repeated' => false, 'name' => "description",    'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],
      "keywords"          => ['required' => false, 'repeated' => false, 'name' => "keywords",       'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],

      "slug"              => ['required' => false, 'repeated' => false, 'name' => "slug",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "ico"               => ['required' => false, 'repeated' => false, 'name' => "ico",            'selector' => "",              'prop' => '',                   'filter' => '',],

      "text"              => ['required' => false, 'repeated' => false, 'name' => "text",           'selector' => "",              'prop' => '',                   'filter' => '',],

      "option_a"          => ['required' => false, 'repeated' => false, 'name' => "option_a",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_b"          => ['required' => false, 'repeated' => false, 'name' => "option_b",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_c"          => ['required' => false, 'repeated' => false, 'name' => "option_c",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_d"          => ['required' => false, 'repeated' => false, 'name' => "option_d",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_e"          => ['required' => false, 'repeated' => false, 'name' => "option_e",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_f"          => ['required' => false, 'repeated' => false, 'name' => "option_f",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_g"          => ['required' => false, 'repeated' => false, 'name' => "option_g",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "type"              => ['required' => false, 'repeated' => false, 'name' => "type",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "status"            => ['required' => false, 'repeated' => false, 'name' => "status",         'selector' => "",              'prop' => '',                   'filter' => '',],

      "answer"            => ['required' => false, 'repeated' => false, 'name' => "answer",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "analysis"          => ['required' => false, 'repeated' => false, 'name' => "analysis",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "parent"            => ['required' => false, 'repeated' => false, 'name' => "parent",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "count"             => ['required' => false, 'repeated' => false, 'name' => "count",          'selector' => "",              'prop' => '',                   'filter' => '',],
      "order"             => ['required' => false, 'repeated' => false, 'name' => "order",          'selector' => "",              'prop' => '',                   'filter' => '',],

      "created_at"        => ['required' => false, 'repeated' => false, 'name' => "created_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "updated_at"        => ['required' => false, 'repeated' => false, 'name' => "updated_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "release_at"        => ['required' => false, 'repeated' => false, 'name' => "release_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "deleted_at"        => ['required' => false, 'repeated' => false, 'name' => "deleted_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "skrbt"                 => [
    'slug'                => 'magnet_skrbt',
    'name'                => '🔴【磁力】SkrBT',
    'title'               => "🔴【磁力】SkrBT",
    'log_show'            => true,
    'log_file'            => 'logs/magnet_skrbt.log',
    'log_type'            => 'info,debug,success,warn,error',
    'log_debug'           => true,
    'cache_path'          => 'cache/magnet_skrbt',
    'max_depth'           => 0,
    'max_fields'          => 0,
    'user_agent'          => phpspider::AGENT_PC,
    'export_type'         => 'db',
    'export_table'        => 'magnet_contents',
    'domains'             => ['skrbtnc.top'],
    'scan_urls'           => ['https://skrbtnc.top/', 'https://skrbtnc.top/search?keyword=%E5%93%AA%E5%90%92%E4%B9%8B%E9%AD%94%E7%AB%A5%E9%99%8D%E4%B8%96'],
    'list_url_regexes'    => ["https://skrbtnc.top/search?\S+"],
    'content_url_regexes' => ["https://skrbtnc.top/detail/\S+"],
    "fields" => [
      "id"                => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => '',                   'filter' => '', "default" => "",  'data_type' => "int", 'nullable' => false, "data_default" => "", "primary_key" => true, "auto_increment" => true],
      "collect_slug"      => ['required' => true,  'repeated' => false, 'name' => "collect_slug",   'selector' => "",              'prop' => 'config.slug',        'filter' => '',  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "collect_status"  => ['required' => false, 'repeated' => false, 'name' => "collect_status",  'selector' => "",              'prop' => '',                   'filter' => '',],
      // "collect_type"   => ['required' => false, 'repeated' => false, 'name' => "collect_type",   'selector' => "",              'prop' => 'page.link.url_type', 'filter' => '',],
      "url"               => ['required' => false, 'repeated' => false, 'name' => "url",            'selector' => "",              'prop' => 'page.url',           'filter' => '', 'data_type' => "varchar(255)", 'nullable' => false,  "data_index" => true,],
      // "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', "default" => "",  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "url_md5"        => ['required' => true,  'repeated' => false, 'name' => "url_md5",        'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', 'data_type' => "varchar(32)", 'nullable' => false,  "data_index" => true,],
      "collect_at"        => ['required' => false, 'repeated' => false, 'name' => "collect_at",     'selector' => "",              'prop' => 'current_timestamp',               'filter' => '', 'data_type' => "varchar(10)",],

      "category"          => ['required' => false, 'repeated' => false, 'name' => "category",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "title"             => ['required' => true,  'repeated' => false, 'name' => "title",          'selector' => "//html//title", 'prop' => '',                   'filter' => '',],
      "description"       => ['required' => false, 'repeated' => false, 'name' => "description",    'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],
      "keywords"          => ['required' => false, 'repeated' => false, 'name' => "keywords",       'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],

      "slug"              => ['required' => false, 'repeated' => false, 'name' => "slug",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "ico"               => ['required' => false, 'repeated' => false, 'name' => "ico",            'selector' => "",              'prop' => '',                   'filter' => '',],

      "text"              => ['required' => false, 'repeated' => false, 'name' => "text",           'selector' => "",              'prop' => '',                   'filter' => '',],

      "option_a"          => ['required' => false, 'repeated' => false, 'name' => "option_a",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_b"          => ['required' => false, 'repeated' => false, 'name' => "option_b",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_c"          => ['required' => false, 'repeated' => false, 'name' => "option_c",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_d"          => ['required' => false, 'repeated' => false, 'name' => "option_d",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_e"          => ['required' => false, 'repeated' => false, 'name' => "option_e",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_f"          => ['required' => false, 'repeated' => false, 'name' => "option_f",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_g"          => ['required' => false, 'repeated' => false, 'name' => "option_g",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "type"              => ['required' => false, 'repeated' => false, 'name' => "type",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "status"            => ['required' => false, 'repeated' => false, 'name' => "status",         'selector' => "",              'prop' => '',                   'filter' => '',],

      "answer"            => ['required' => false, 'repeated' => false, 'name' => "answer",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "analysis"          => ['required' => false, 'repeated' => false, 'name' => "analysis",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "parent"            => ['required' => false, 'repeated' => false, 'name' => "parent",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "count"             => ['required' => false, 'repeated' => false, 'name' => "count",          'selector' => "",              'prop' => '',                   'filter' => '',],
      "order"             => ['required' => false, 'repeated' => false, 'name' => "order",          'selector' => "",              'prop' => '',                   'filter' => '',],

      "created_at"        => ['required' => false, 'repeated' => false, 'name' => "created_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "updated_at"        => ['required' => false, 'repeated' => false, 'name' => "updated_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "release_at"        => ['required' => false, 'repeated' => false, 'name' => "release_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "deleted_at"        => ['required' => false, 'repeated' => false, 'name' => "deleted_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "laowanghv"             => [
    'slug'                => 'magnet_laowanghv',
    'name'                => '🔴【磁力】老王磁力',
    'title'               => "🔴【磁力】老王磁力",
    'log_show'            => true,
    'log_file'            => 'logs/magnet_skrbt.log',
    'log_type'            => 'info,debug,success,warn,error',
    'log_debug'           => true,
    'cache_path'          => 'cache/magnet_laowanghv',
    'max_depth'           => 0,
    'max_fields'          => 0,
    'user_agent'          => phpspider::AGENT_PC,
    'export_type'         => 'db',
    'export_table'        => 'magnet_contents',
    'domains'             => ['laowanghv.top'],
    'scan_urls'           => ['https://laowanghv.top/', 'https://laowanghv.top/search?keyword=%E7%A7%A6%E5%B2%AD%E7%A5%9E%E6%A0%91'],
    'list_url_regexes'    => ["https://laowanghv.top/search?\S+"],
    'content_url_regexes' => ["https://laowanghv.top/detail/\S+"],
    "fields" => [
      "id"                => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => '',                   'filter' => '', "default" => "",  'data_type' => "int", 'nullable' => false, "data_default" => "", "primary_key" => true, "auto_increment" => true],
      "collect_slug"      => ['required' => true,  'repeated' => false, 'name' => "collect_slug",   'selector' => "",              'prop' => 'config.slug',        'filter' => '',  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "collect_status"  => ['required' => false, 'repeated' => false, 'name' => "collect_status",  'selector' => "",              'prop' => '',                   'filter' => '',],
      // "collect_type"   => ['required' => false, 'repeated' => false, 'name' => "collect_type",   'selector' => "",              'prop' => 'page.link.url_type', 'filter' => '',],
      "url"               => ['required' => false, 'repeated' => false, 'name' => "url",            'selector' => "",              'prop' => 'page.url',           'filter' => '', 'data_type' => "varchar(255)", 'nullable' => false,  "data_index" => true,],
      // "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', "default" => "",  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "url_md5"        => ['required' => true,  'repeated' => false, 'name' => "url_md5",        'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', 'data_type' => "varchar(32)", 'nullable' => false,  "data_index" => true,],
      "collect_at"        => ['required' => false, 'repeated' => false, 'name' => "collect_at",     'selector' => "",              'prop' => 'current_timestamp',               'filter' => '', 'data_type' => "varchar(10)",],

      "category"          => ['required' => false, 'repeated' => false, 'name' => "category",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "title"             => ['required' => true,  'repeated' => false, 'name' => "title",          'selector' => "//html//title", 'prop' => '',                   'filter' => '',],
      "description"       => ['required' => false, 'repeated' => false, 'name' => "description",    'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],
      "keywords"          => ['required' => false, 'repeated' => false, 'name' => "keywords",       'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],

      "slug"              => ['required' => false, 'repeated' => false, 'name' => "slug",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "ico"               => ['required' => false, 'repeated' => false, 'name' => "ico",            'selector' => "",              'prop' => '',                   'filter' => '',],

      "text"              => ['required' => false, 'repeated' => false, 'name' => "text",           'selector' => "",              'prop' => '',                   'filter' => '',],

      "option_a"          => ['required' => false, 'repeated' => false, 'name' => "option_a",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_b"          => ['required' => false, 'repeated' => false, 'name' => "option_b",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_c"          => ['required' => false, 'repeated' => false, 'name' => "option_c",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_d"          => ['required' => false, 'repeated' => false, 'name' => "option_d",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_e"          => ['required' => false, 'repeated' => false, 'name' => "option_e",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_f"          => ['required' => false, 'repeated' => false, 'name' => "option_f",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_g"          => ['required' => false, 'repeated' => false, 'name' => "option_g",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "type"              => ['required' => false, 'repeated' => false, 'name' => "type",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "status"            => ['required' => false, 'repeated' => false, 'name' => "status",         'selector' => "",              'prop' => '',                   'filter' => '',],

      "answer"            => ['required' => false, 'repeated' => false, 'name' => "answer",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "analysis"          => ['required' => false, 'repeated' => false, 'name' => "analysis",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "parent"            => ['required' => false, 'repeated' => false, 'name' => "parent",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "count"             => ['required' => false, 'repeated' => false, 'name' => "count",          'selector' => "",              'prop' => '',                   'filter' => '',],
      "order"             => ['required' => false, 'repeated' => false, 'name' => "order",          'selector' => "",              'prop' => '',                   'filter' => '',],

      "created_at"        => ['required' => false, 'repeated' => false, 'name' => "created_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "updated_at"        => ['required' => false, 'repeated' => false, 'name' => "updated_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "release_at"        => ['required' => false, 'repeated' => false, 'name' => "release_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "deleted_at"        => ['required' => false, 'repeated' => false, 'name' => "deleted_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "soucili"               => [
    'slug'                => 'magnet_soucili',
    'name'                => '🔴【磁力】老王磁力',
    'title'               => "🔴【磁力】老王磁力",
    'log_show'            => true,
    'log_file'            => 'logs/magnet_skrbt.log',
    'log_type'            => 'info,debug,success,warn,error',
    'log_debug'           => true,
    'cache_path'          => 'cache/magnet_soucili',
    'max_depth'           => 0,
    'max_fields'          => 0,
    'user_agent'          => phpspider::AGENT_PC,
    'export_type'         => 'db',
    'export_table'        => 'magnet_contents',
    'domains'             => ['soucili91.com', 'oldeseo.soucili91.com'],
    'scan_urls'           => ['https://oldeseo.soucili91.com/', 'https://oldeseo.soucili91.com/search_plus_a.php?keywords=%E7%A7%A6%E5%B2%AD%E7%A5%9E%E6%A0%91'],
    'list_url_regexes'    => ["https://oldeseo.soucili91.com/search_plus_a.php?\S+"],
    'content_url_regexes' => ["https://oldeseo.soucili91.com/search_plus_a.php?\S+"],
    "fields" => [
      "id"                => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => '',                   'filter' => '', "default" => "",  'data_type' => "int", 'nullable' => false, "data_default" => "", "primary_key" => true, "auto_increment" => true],
      "collect_slug"      => ['required' => true,  'repeated' => false, 'name' => "collect_slug",   'selector' => "",              'prop' => 'config.slug',        'filter' => '',  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "collect_status"  => ['required' => false, 'repeated' => false, 'name' => "collect_status",  'selector' => "",              'prop' => '',                   'filter' => '',],
      // "collect_type"   => ['required' => false, 'repeated' => false, 'name' => "collect_type",   'selector' => "",              'prop' => 'page.link.url_type', 'filter' => '',],
      "url"               => ['required' => false, 'repeated' => false, 'name' => "url",            'selector' => "",              'prop' => 'page.url',           'filter' => '', 'data_type' => "varchar(255)", 'nullable' => false,  "data_index" => true,],
      // "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', "default" => "",  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "url_md5"        => ['required' => true,  'repeated' => false, 'name' => "url_md5",        'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', 'data_type' => "varchar(32)", 'nullable' => false,  "data_index" => true,],
      "collect_at"        => ['required' => false, 'repeated' => false, 'name' => "collect_at",     'selector' => "",              'prop' => 'current_timestamp',               'filter' => '', 'data_type' => "varchar(10)",],

      "category"          => ['required' => false, 'repeated' => false, 'name' => "category",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "title"             => ['required' => true,  'repeated' => false, 'name' => "title",          'selector' => "//html//title", 'prop' => '',                   'filter' => '',],
      "description"       => ['required' => false, 'repeated' => false, 'name' => "description",    'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],
      "keywords"          => ['required' => false, 'repeated' => false, 'name' => "keywords",       'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],

      "slug"              => ['required' => false, 'repeated' => false, 'name' => "slug",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "ico"               => ['required' => false, 'repeated' => false, 'name' => "ico",            'selector' => "",              'prop' => '',                   'filter' => '',],

      "text"              => ['required' => false, 'repeated' => false, 'name' => "text",           'selector' => "",              'prop' => '',                   'filter' => '',],

      "option_a"          => ['required' => false, 'repeated' => false, 'name' => "option_a",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_b"          => ['required' => false, 'repeated' => false, 'name' => "option_b",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_c"          => ['required' => false, 'repeated' => false, 'name' => "option_c",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_d"          => ['required' => false, 'repeated' => false, 'name' => "option_d",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_e"          => ['required' => false, 'repeated' => false, 'name' => "option_e",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_f"          => ['required' => false, 'repeated' => false, 'name' => "option_f",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_g"          => ['required' => false, 'repeated' => false, 'name' => "option_g",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "type"              => ['required' => false, 'repeated' => false, 'name' => "type",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "status"            => ['required' => false, 'repeated' => false, 'name' => "status",         'selector' => "",              'prop' => '',                   'filter' => '',],

      "answer"            => ['required' => false, 'repeated' => false, 'name' => "answer",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "analysis"          => ['required' => false, 'repeated' => false, 'name' => "analysis",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "parent"            => ['required' => false, 'repeated' => false, 'name' => "parent",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "count"             => ['required' => false, 'repeated' => false, 'name' => "count",          'selector' => "",              'prop' => '',                   'filter' => '',],
      "order"             => ['required' => false, 'repeated' => false, 'name' => "order",          'selector' => "",              'prop' => '',                   'filter' => '',],

      "created_at"        => ['required' => false, 'repeated' => false, 'name' => "created_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "updated_at"        => ['required' => false, 'repeated' => false, 'name' => "updated_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "release_at"        => ['required' => false, 'repeated' => false, 'name' => "release_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "deleted_at"        => ['required' => false, 'repeated' => false, 'name' => "deleted_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
];
