<?php return [
  "default" => [
    'slug' => 'question_',
    'name' => '🔴🟡🟢【试题】',
    'title' => "【试题】",
    'log_show' => true,
    'log_file' => 'logs/question_.log',
    'log_type' => 'error',
    'log_debug' => true,
    'cache_path' => 'cache/question_',
    'max_depth' => 0,
    'max_fields' => 0,
    'export_type' => 'db',
    'export_table' => 'question_contents',
    'domains' => [],
    'scan_urls' => [],
    'list_url_regexes' => [],
    'content_url_regexes' => [],
    "fields" => [
      "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => '',                   'filter' => '', "default" => "",  'data_type' => "int", 'nullable' => false, "data_default" => "", "primary_key" => true, "auto_increment" => true],
      "collect_slug"   => ['required' => true,  'repeated' => false, 'name' => "collect_slug",   'selector' => "",              'prop' => 'config.slug',        'filter' => '',  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "collect_status"  => ['required' => false, 'repeated' => false, 'name' => "collect_status",  'selector' => "",              'prop' => '',                   'filter' => '',],
      // "collect_type"   => ['required' => false, 'repeated' => false, 'name' => "collect_type",   'selector' => "",              'prop' => 'page.link.url_type', 'filter' => '',],
      "url"            => ['required' => false, 'repeated' => false, 'name' => "url",            'selector' => "",              'prop' => 'page.url',           'filter' => '', 'data_type' => "varchar(255)", 'nullable' => false,  "data_index" => true,],
      // "id"             => ['required' => false, 'repeated' => false, 'name' => "id",             'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', "default" => "",  'data_type' => "varchar(32)", 'nullable' => false, "data_default" => "", "data_index" => true],
      // "url_md5"        => ['required' => true,  'repeated' => false, 'name' => "url_md5",        'selector' => "",              'prop' => 'page.url',           'filter' => 'md5', 'data_type' => "varchar(32)", 'nullable' => false,  "data_index" => true,],
      "collect_at"     => ['required' => false, 'repeated' => false, 'name' => "collect_at",     'selector' => "",              'prop' => 'current_timestamp',               'filter' => '', 'data_type' => "varchar(10)",],

      "category"       => ['required' => false, 'repeated' => false, 'name' => "category",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "title"          => ['required' => true,  'repeated' => false, 'name' => "title",          'selector' => "//html//title", 'prop' => '',                   'filter' => '',],
      "description"    => ['required' => false, 'repeated' => false, 'name' => "description",    'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],
      "keywords"       => ['required' => false, 'repeated' => false, 'name' => "keywords",       'selector' => "//html//meta",  'prop' => '',                   'filter' => '',],

      "slug"           => ['required' => false, 'repeated' => false, 'name' => "slug",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "ico"            => ['required' => false, 'repeated' => false, 'name' => "ico",            'selector' => "",              'prop' => '',                   'filter' => '',],

      "text"           => ['required' => false, 'repeated' => false, 'name' => "text",           'selector' => "",              'prop' => '',                   'filter' => '',],

      "option_a"       => ['required' => false, 'repeated' => false, 'name' => "option_a",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_b"       => ['required' => false, 'repeated' => false, 'name' => "option_b",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_c"       => ['required' => false, 'repeated' => false, 'name' => "option_c",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_d"       => ['required' => false, 'repeated' => false, 'name' => "option_d",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_e"       => ['required' => false, 'repeated' => false, 'name' => "option_e",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_f"       => ['required' => false, 'repeated' => false, 'name' => "option_f",       'selector' => "",              'prop' => '',                   'filter' => '',],
      "option_g"       => ['required' => false, 'repeated' => false, 'name' => "option_g",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "type"           => ['required' => false, 'repeated' => false, 'name' => "type",           'selector' => "",              'prop' => '',                   'filter' => '',],
      "status"         => ['required' => false, 'repeated' => false, 'name' => "status",         'selector' => "",              'prop' => '',                   'filter' => '',],

      "answer"         => ['required' => false, 'repeated' => false, 'name' => "answer",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "analysis"       => ['required' => false, 'repeated' => false, 'name' => "analysis",       'selector' => "",              'prop' => '',                   'filter' => '',],

      "parent"         => ['required' => false, 'repeated' => false, 'name' => "parent",         'selector' => "",              'prop' => '',                   'filter' => '',],
      "count"          => ['required' => false, 'repeated' => false, 'name' => "count",          'selector' => "",              'prop' => '',                   'filter' => '',],
      "order"          => ['required' => false, 'repeated' => false, 'name' => "order",          'selector' => "",              'prop' => '',                   'filter' => '',],

      "created_at"     => ['required' => false, 'repeated' => false, 'name' => "created_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "updated_at"     => ['required' => false, 'repeated' => false, 'name' => "updated_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "release_at"     => ['required' => false, 'repeated' => false, 'name' => "release_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
      "deleted_at"     => ['required' => false, 'repeated' => false, 'name' => "deleted_at",     'selector' => "",              'prop' => '',                   'filter' => '', 'data_type' => "varchar(10)",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "asklib" => [
    'slug' => 'question_asklib',
    'name' => '🟡【试题】问答库',
    'title' => "试题：问答库",
    'log_show' => true,
    'log_file' => 'logs/question_asklib.log',
    'log_type' => 'error',
    'max_depth' => 1,
    'max_fields' => 2,
    'export' => [
      'type' => 'csv',
      'file' => './data/question_asklib.csv', // data目录下
    ],
    'domains' => [
      'asklib.com',
      'www.asklib.com',
    ],
    'scan_urls' => [
      // "https://www.asklib.com",
      "https://www.asklib.com/view/1e05e29c.html",
    ],
    'list_url_regexes' => [
      "https://www.asklib.com/.+",
    ],
    'content_url_regexes' => [
      "https://www.asklib.com/view/\S+.html",
    ],
    "fields" => [
      'category' => ['name' => "category", 'selector' => "//*[contains(@class,'seotops')]/a", 'filter' => '',],
      'title' => ['name' => "title",        'selector' => "//*[contains(@class,'essaytitle')]//h1",        'filter' => '',        'required' => true],
      'content' => ['name' => "content",        'selector' => "//*[contains(@class,'essaytitle')]/p[last()]",        'filter' => '',        'required' => true],
      'type' => ['name' => "type",        'selector' => "//*[contains(@class,'essaytitle')]//h1",        'filter' => '',],
      'answer' => ['name' => "answer",        'selector' => "//*[contains(@class,'listbg')]//text()",        'filter' => '',],
      'analysis' => ['name' => "analysis",        'selector' => "//*[contains(@id,'commentDiv')]//p",        'filter' => '',],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "haodaxue" => [
    'slug'                           => 'question_haodaxue',
    'name'                           => '🟢【试题】好大学',
    'title'                          => "🟢【试题】好大学",
    "extends"                        => "default:question",
    'queue_prefix'                   => 'phpspider:question_contents:haodaxue',
    'domains' => [
      // 'haodaxue.net',
      'www.haodaxue.net',
    ],
    'scan_urls' => [
      "https://www.haodaxue.net/",
      // "https://www.haodaxue.net/shiti/103800.html",
    ],
    'list_url_regexes' => [
      "https://www.haodaxue.net/.+",
    ],
    'content_url_regexes' => [
      "https://www.haodaxue.net/shiti/\d+.html",
    ],
    "fields" => [
      'category' => ['name' => "category",        'selector' => "/html/body/div[3]/div/a[position()>2 and position()<last()]",        'filter' => '',        'repeated' => true,],
      'title' => ['name' => "title",        'selector' => '//*[@id="Min_L"]/div[1]/h1/p',       'filter' => '',        'required' => true],
      'content' => ['name' => "content",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li',        'filter' => '',        'repeated' => true,       'required' => true],
      'option_a' => ['name' => "option_a",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[1]/text()', 'filter' => 'tirm',],
      'option_b' => ['name' => "option_b",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[2]/text()', 'filter' => 'tirm',],
      'option_c' => ['name' => "option_c",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[3]/text()', 'filter' => 'tirm',],
      'option_d' => ['name' => "option_d",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[4]/text()', 'filter' => 'tirm',],
      'option_e' => ['name' => "option_e",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[5]/text()', 'filter' => 'tirm',],
      'option_f' => ['name' => "option_f",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[6]/text()', 'filter' => 'tirm',],
      'option_g' => ['name' => "option_g",        'selector' => '//*[@id="Min_L"]/div[1]/ul//li[7]/text()', 'filter' => 'tirm',],
      'type' => ['name' => "type",        'selector' => "//*[contains(@class,'essaytitle')]//h1",        'filter' => '',],
      'answer' => ['name' => "answer",        'selector' => '//*[@id="Min_L"]/div[1]/div/div[4]/p[1]/strong',        'filter' => 'trim',],
      'analysis' => ['name' => "analysis",        'selector' => '//*[@id="Min_L"]/div[1]/div/div[4]/p[2]/text()',        'filter' => 'trim',],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
  "mianshiya" => [
    'slug' => 'question_mianshiya',
    'name' => '🟡【试题】',
    'title' => "🟡【试题】",
    'log_show' => true,
    'log_file' => 'logs/question_mianshiya.log',
    'log_type' => 'error',
    'max_depth' => 1,
    'max_fields' => 2,
    'export' => [
      'type' => 'csv',
      'file' => './data/question_mianshiya.csv', // data目录下
    ],
    'domains' => ["mianshiya.com", "www.mianshiya.com"],
    'scan_urls' => [
      // "https://www.mianshiya.com/bank/1860931478862618626/question/1817828882598879234",
      // "https://www.mianshiya.com/bank/1860871861809897474/question/1824003166933868546",
      "https://www.mianshiya.com/bank/1860871861809897474/question/1780933295467425794",
    ],
    'list_url_regexes' => [],
    'content_url_regexes' => [
      "https://www.mianshiya.com/bank/\d+/question/\d+"
    ],
    "fields" => [
      'category' =>  ['name' => "category",        'selector' => "",],
      'title' =>  ['name' => "title",        'selector' => "//*[@id='question-main']/div[1]/div/div/h1/div",        'required' => true,],
      'content' =>  ['name' => "content",        'selector' => "",],
      'option_a' =>  ['name' => "option_a",        'selector' => "",],
      'option_b' =>  ['name' => "option_b",        'selector' => "",],
      'option_c' =>  ['name' => "option_c",        'selector' => "",],
      'option_d' =>  ['name' => "option_d",        'selector' => "",],
      'option_e' =>  ['name' => "option_e",        'selector' => "",],
      'option_f' =>  ['name' => "option_f",        'selector' => "",],
      'option_g' => ['name' => "option_g",        'selector' => "",],
      'type' => ['name' => "type",        'selector' => "",],
      'answer' => ['name' => "answer",        'selector' => "",],
      'analysis' => ['name' => "analysis",        'selector' => "//*[@id='answer-comment-card']/div[2]/div[1]/div[1]/div",],
      'created_at' => ['name' => "created_at",        'selector' => "",],
      'updated_at' => ['name' => "updated_at",        'selector' => "",],
      'release_at' => ['name' => "release_at",        'selector' => "",],
      'deleted_at' => ['name' => "deleted_at",        'selector' => "",],
    ],
    "rules" => [],
    "methods" => [
      "on_start" => NULL,
      "on_before_download_page" => NULL,
      "on_status_code" => NULL,
      "is_anti_spider" =>  NULL,
      "on_download_page" =>  NULL,
      "on_download_attached_page" =>  NULL,
      "on_fetch_url" =>  NULL,
      "on_scan_page" =>  NULL,
      "on_list_page" =>  NULL,
      "on_content_page" =>  NULL,
      "on_handle_img" =>  NULL,
      "on_extract_field" =>  NULL,
      "on_extract_page" =>  NULL,
      "on_attachment_file" =>  NULL,
    ]
  ],
];
