
[common]
# server_addr为FRPS服务器IP地址
server_addr = 101.126.135.139
# server_port为服务端监听端口，bind_port
server_port = 7000
# 身份验证
token = langnang.com
# includes = ["/etc/frp/confd/*.toml"]

webServer_addr = "127.0.0.1"#监听地址，默认为 127.0.0.1。
webServer_port = 7400 #【必填】监听端口。
webServer_user = "admin"#仪表盘用户名。
webServer_password = "admin1234"#仪表盘密码。

#? http://127.0.0.1:7400

[{{ .Envs.DEVICE_NAME }}::SSH] 
type = tcp
local_ip = host.docker.internal
local_port = 22
remote_port = 22012

[{{ .Envs.DEVICE_NAME }}::RDP]
type = tcp
local_ip = host.docker.internal
local_port = 3389
remote_port = 38912

[{{ .Envs.DEVICE_NAME }}::Cpolar]
type = tcp
local_ip = host.docker.internal
local_port = 9200
remote_port = 29012
# http://101.126.135.139:29012

[{{ .Envs.DEVICE_NAME }}::PortainterAgent]
type = tcp
local_ip = portainer-agent
local_port = 9001
remote_port = 9012

