links:
  - name: "Home"
    icon: "fas fa-home"
    url: "#"
  - name: "Coding"
    icon: "fas fa-layer-group"
    url: "#subs/coding"

services:
  - name: "HOST-Win10-Desktop"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:811/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9211/"
      - name: "DPanel"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:8011/"
      - name: "Portainer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9011/"

  - name: "HOST-Win10-Laptop"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:812/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9212/"

  - name: "VM-CentOS-8"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:851/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9251/"
      - name: "DPanel"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:8051/"

  - name: "VM-Debian-13"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:852/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9252/"
      - name: "DPanel"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:8052/"

  - name: "VM-Ubuntu-24"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:853/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9253/"
      - name: "DPanel"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:8053/"

  - name: "VM-FedoraServer-40"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:871/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9271/"
      - name: "MySQL"
        logo: "https://cdn.simpleicons.org/mysql"
        url: "./adminer//?server=host.docker.internal"
        target: "_blank"
      - name: "PostgreSQL"
        logo: "https://cdn.simpleicons.org/postgresql"
        target: "_blank"
      - name: "Redis"
        logo: "https://cdn.simpleicons.org/Redis"
        target: "_blank"
      - name: "MongoDB"
        logo: "https://cdn.simpleicons.org/MongoDB"
        target: "_blank"
      - name: "InfluxDB"
        logo: "https://cdn.simpleicons.org/InfluxDB"
        target: "_blank"
      - name: "Memcached"
        logo: "assets/tools/sample2.png"
        target: "_blank"

  - name: "VM-FedoraServer-42"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:872/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9272/"
      - name: "MySQL"
        logo: "https://cdn.simpleicons.org/mysql"
        url: "./adminer//?server=host.docker.internal"
        target: "_blank"
      - name: "PostgreSQL"
        logo: "https://cdn.simpleicons.org/postgresql"
        target: "_blank"
      - name: "Redis"
        logo: "https://cdn.simpleicons.org/Redis"
        target: "_blank"
      - name: "MongoDB"
        logo: "https://cdn.simpleicons.org/MongoDB"
        target: "_blank"
      - name: "InfluxDB"
        logo: "https://cdn.simpleicons.org/InfluxDB"
        target: "_blank"
      - name: "Memcached"
        logo: "assets/tools/sample2.png"
        target: "_blank"

  - name: "VM-UbuntuServer-18"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:873/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9273/"
      - name: "MySQL"
        logo: "https://cdn.simpleicons.org/mysql"
        url: "./adminer//?server=host.docker.internal"
        target: "_blank"
      - name: "PostgreSQL"
        logo: "https://cdn.simpleicons.org/postgresql"
        target: "_blank"
      - name: "Redis"
        logo: "https://cdn.simpleicons.org/Redis"
        target: "_blank"
      - name: "MongoDB"
        logo: "https://cdn.simpleicons.org/MongoDB"
        target: "_blank"
      - name: "InfluxDB"
        logo: "https://cdn.simpleicons.org/InfluxDB"
        target: "_blank"
      - name: "Memcached"
        logo: "assets/tools/sample2.png"
        target: "_blank"

  - name: "VM-UbuntuServer-22"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:874/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9274/"
      - name: "MySQL"
        logo: "https://cdn.simpleicons.org/mysql"
        url: "./adminer//?server=host.docker.internal"
        target: "_blank"
      - name: "PostgreSQL"
        logo: "https://cdn.simpleicons.org/postgresql"
        target: "_blank"
      - name: "Redis"
        logo: "https://cdn.simpleicons.org/Redis"
        target: "_blank"
      - name: "MongoDB"
        logo: "https://cdn.simpleicons.org/MongoDB"
        target: "_blank"
      - name: "InfluxDB"
        logo: "https://cdn.simpleicons.org/InfluxDB"
        target: "_blank"
      - name: "Memcached"
        logo: "assets/tools/sample2.png"
        target: "_blank"

  - name: "VM-UbuntuServer-24"
    icon: "fas fa-cloud"
    items:
      - name: "Homer"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:875/"
      - name: "Cpolar"
        type: "Ping"
        logo: "assets/tools/sample.png"
        target: "_blank"
        url: "http://101.126.135.139:9275/"
      - name: "MySQL"
        logo: "https://cdn.simpleicons.org/mysql"
        url: "./adminer//?server=host.docker.internal"
        target: "_blank"
      - name: "PostgreSQL"
        logo: "https://cdn.simpleicons.org/postgresql"
        target: "_blank"
      - name: "Redis"
        logo: "https://cdn.simpleicons.org/Redis"
        target: "_blank"
      - name: "MongoDB"
        logo: "https://cdn.simpleicons.org/MongoDB"
        target: "_blank"
      - name: "InfluxDB"
        logo: "https://cdn.simpleicons.org/InfluxDB"
        target: "_blank"
      - name: "Memcached"
        logo: "assets/tools/sample2.png"
        target: "_blank"

  - name: "ByetHost-b7_34048879"
    icon: "fas fa-cloud"
    items:

  - name: "ByetHost-b11_37611028"
    icon: "fas fa-cloud"
    items:

  - name: "ByetHost-b14_37610952"
    icon: "fas fa-cloud"
    items:

  - name: "ByetHost-b32_28202196"
    icon: "fas fa-cloud"
    items:
