-- Modules\Admin\Database\Seeders\AdminDatabaseSeeder
-- 2025-08-12 17:19:44

select * from `_metas` where `slug` = 'admin' and `_metas`.`deleted_at` is null limit 1

insert into `_metas` (`created_at`, `ico`, `name`, `order`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:43', 'fas fa-tachometer-alt', '仪表板', 1, 2, 'admin:dashboard', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', 'fas fa-tachometer-alt', '聚合数据', 2, 2, 'admin:ssential', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', 'fas fa-tachometer-alt', '模块管理', 3, 2, 'admin:modules', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', 'fas fa-tachometer-alt', '框架管理', 4, 2, 'admin:framework', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', 'fas fa-tachometer-alt', '系统管理', 5, 2, 'admin:system', 'public', 'category', '2025-08-12 17:19:43') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `order` = values(`order`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

select * from `_metas` where `slug` = 'admin:ssential' and `_metas`.`deleted_at` is null limit 1

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:43', '', 'Metas', 29, 'admin:ssential:metas', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', '', 'Contents', 29, 'admin:ssential:contents', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', '', 'Links', 29, 'admin:ssential:links', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', '', 'Files', 29, 'admin:ssential:files', 'public', 'category', '2025-08-12 17:19:43'), ('2025-08-12 17:19:43', '', 'Spiders', 29, 'admin:ssential:spiders', 'public', 'category', '2025-08-12 17:19:43') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

select * from `_metas` where `slug` = 'admin:modules' and `_metas`.`deleted_at` is null limit 1

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Application', 30, 'admin:modules:application', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Audio', 30, 'admin:modules:audio', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Awesome', 30, 'admin:modules:awesome', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Blog', 30, 'admin:modules:blog', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'CheatSheet', 30, 'admin:modules:cheatsheet', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Dependency', 30, 'admin:modules:dependency', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Home', 30, 'admin:modules:home', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Manual', 30, 'admin:modules:manual', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Market', 30, 'admin:modules:market', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Novel', 30, 'admin:modules:novel', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Plan', 30, 'admin:modules:plan', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Project', 30, 'admin:modules:project', 'private', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'PublicApi', 30, 'admin:modules:publicapi', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Question', 30, 'admin:modules:question', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'School', 30, 'admin:modules:school', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Snippet', 30, 'admin:modules:snippet', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Software', 30, 'admin:modules:software', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Toolkit', 30, 'admin:modules:toolkit', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'WebFrame', 30, 'admin:modules:webframe', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'WebHunt', 30, 'admin:modules:webhunt', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'WebNav', 30, 'admin:modules:webnav', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'WebPage', 30, 'admin:modules:webpage', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'WebSpider', 30, 'admin:modules:webspider', 'private', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'WebTerminal', 30, 'admin:modules:webterminal', 'private', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Wiki', 30, 'admin:modules:wiki', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

select * from `_metas` where `slug` = 'admin:framework' and `_metas`.`deleted_at` is null limit 1

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', 'Options', 31, 'admin:framework:options', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', 'Caches', 31, 'admin:framework:caches', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', 'Sessions', 31, 'admin:framework:sessions', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', 'Logs', 31, 'admin:framework:logs', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', 'Migrations', 31, 'admin:framework:migrations', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', 'Seeders', 31, 'admin:framework:seeders', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)

select * from `_metas` where `slug` = 'admin:system' and `_metas`.`deleted_at` is null limit 1

insert into `_metas` (`created_at`, `ico`, `name`, `parent`, `slug`, `status`, `type`, `updated_at`) values ('2025-08-12 17:19:44', '', '应用市场', 32, 'admin:system:market', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', '用户管理', 32, 'admin:system:user', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', '数据管理', 32, 'admin:system:database', 'public', 'category', '2025-08-12 17:19:44'), ('2025-08-12 17:19:44', '', '资源管理', 32, 'admin:system:storage', 'public', 'category', '2025-08-12 17:19:44') on duplicate key update `slug` = values(`slug`), `ico` = values(`ico`), `name` = values(`name`), `type` = values(`type`), `status` = values(`status`), `parent` = values(`parent`), `updated_at` = values(`updated_at`)
