networks:
  software-network:
    external: true
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr_data:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${HOMARR_ENCRYPTION_KEY:-2dff4b06831e4608cc93dfee6fbe55b29ff0ee189cafd23ccc128698dae55884}
    ports:
      - "7575"
    labels:
      yantr.app: "homarr"
      yantr.service: "Dashboard"
  # homarr:
  #   image: ajnart/homarr:latest
  #   container_name: homarr
  #   ports:
  #     - "0:7575"
  #   volumes:
  #     # - /data/homarr/configs:/app/data/configs
  #     # - /data/homarr/icons:/app/public/icons
  #     - //var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped
  #   networks:
  #     - software-network

volumes:
  homarr_data:
