networks:
  software-network:
    external: true
services:
  latest:
    image: missuo/freegpt35
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 0:3040
    restart: unless-stopped
    networks:
      - software-network
