devices:
  # -:
  #   device_type:
  # -Linux:
  #   device_type:
  # -LinuxServer:
  #   device_type: Linux
  # -Windows:
  #   device_type:
  # -WindowsServer:
  #   device_type: Windows
  # HOST-fnOS-37:
  # HOST-Win10-Desktop:
  #   device_type:
  #   commands:
  #     - docker restart compose-nginx-1
  #     - docker restart compose-frpc-1
  # HOST-Win10-Laptop:
  #   root_name:
  #   root_pass:
  #   user_name:
  #   user_pass:
  #   device_addr:
  #   device_type: Windows
  #   device_name:
  #   device_netk:
  #   device_soln:
  #   commands:
  #     - docker restart compose-nginx-1
  #     - docker restart compose-frpc-1
  # VM-CentOS-8:
  # VM-Debian-13:
  # VM-FedoraServer-40:
  # VM-FedoraServer-42:
  # VM-fnOS-37:
  VM-Ubuntu-24:
    root:
      name:
      pass:

    user:
      name: administrator
      pass: root

    device:
      addr: 192.168.194.135
      type:
      name: VM-Ubuntu-24

    applications:
      cpolar:
        version: 3.3.12
      docker:
        version: 28.4.0
      docker-compose:
        version: 2.39.4

    softwares:
      frpc:
        - ftp
        - ssh
        - cpolar
        - portainer-agent
        - nginx-80

    networks:

    solutions:

    commands:
  # VM-UbuntuServer-18:
  #   device_type: LinuxServer
  # VM-UbuntuServer-22:
  #   device_type: LinuxServer
  # VM-UbuntuServer-24:
  #   device_type: LinuxServer
  # VolcEngine-ECS-Debian-12:
  #   root:
  #     name:
  #     pass:

  #   user:
  #     name: root
  #     pass: chenLL!995

  #   device:
  #     addr: 101.126.135.139
  #     type:
  #     name: VolcEngine-ECS-Debian-12

  #   applications:
  #     cpolar:
  #       version: 3.3.12
  #     docker:
  #       version: 28.5.0
  #     docker-compose:
  #       version:

  #   softwares:

  #   networks:

  #   solutions:

  #   commands:
  #     - docker restart compose-nginx-1
  #     - docker restart compose-frps-1
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/docker-compose.yml root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/docker-compose.host.yml root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/frpc root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/frps root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/homer root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/nginx root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/portainer root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/smartping root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/vaultwarden root@101.126.135.139:/app/
  #     # - scp -r D:/wwwroot/@Langnang/_configs/@docker/esc-debian-12/prometheus root@101.126.135.139:/app/
  #     # - ssh root@101.126.135.139 "cd /app; docker compose -f docker-compose.yml up -d --build;"
  #     # - ssh root@101.126.135.139 "cd /app; docker compose -f docker-compose.host.yml up -d  --build;"
  #     # - ssh root@101.126.135.139 "cd /app; docker restart app-frps-1;"
  #     # - docker-compose -f 'D:\wwwroot\@Langnang\_configs\@docker\esc-debian-12\docker-compose.yml' up -d --build
  #     # - docker-compose -f 'D:\wwwroot\@Langnang\_configs\@docker\esc-debian-12\docker-compose.host.yml' up -d --build
  #     # - docker restart esc-debian-12-nginx-1
networks:
  network_software:
    # docker_services:
    append_softwares:
      # - transmission
      # - moviepilot-v2
      - qbittorrent
      - grafana
      - ariang
      # - jackett
      # - home-assistant
      # - surveyking
      - nginx-proxy-manager
    softwares:
      homer:
        config:
    commands:
      - compose -f 'D:\wwwroot\@Langnang\_configs\@docker\network_software\docker-compose.yml' up -d --build
      - docker restart network_software-nginx-1

solutions:
  solution_cinema:
    vmware: Ubuntu-Server-24
    commands:
      - scp -r D:/wwwroot/@Langnang/_configs/@docker/solution_cinema/docker-compose.yml administrator@192.168.194.133:/app/
      - scp -r D:/wwwroot/@Langnang/_configs/@docker/solution_cinema/homer administrator@192.168.194.133:/app/
      - scp -r D:/wwwroot/@Langnang/_configs/@docker/solution_cinema/nginx administrator@192.168.194.133:/app/
      - ssh administrator@192.168.194.133 "cd /app; docker compose up -d;"
