services:
  frpc:
    image: snowdreamtech/frpc
    environment:
      - DEVICE_NAME=VM-UbuntuServer-24
      - DEVICE_CODE=73
    volumes:
      - ./frpc/frpc.toml:/etc/frp/frpc.toml
    restart: unless-stopped
  portainer-agent:
    image: portainer/agent
    ports:
      - 9001:9001
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
