services:
  homer:
    image: b4bz/homer:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - ./homer/subs:/www/assets/subs
      - ./homer/custom.css:/www/assets/custom.css
      - ./homer/config.yml:/www/assets/config.yml
    # ports:
    #   - 8580:8080
    restart: unless-stopped

  adminer:
    image: adminer:latest
    # ports:
    #   - 0:8080
    # volumes:
    #   - adminer-plugins:/var/www/html/plugins-enabled
    restart: unless-stopped
