networks:
  software-network:
    external: true
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    labels:
      yantr.app: "mongodb"
      yantr.service: "NoSQL Database"
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  # mongo:
  #   image: mongo:4.2
  #   restart: unless-stopped
  #   networks:
  #     - software-network

volumes:
  mongodb_data:
