# 未配置容器 postgresql 的暴露端口 
# 未配置容器 redis 的暴露端口 
# 未配置容器 memcached 的暴露端口 
# 未配置容器 influxdb 的暴露端口 
# 未配置容器 mongodb 的暴露端口 
# 未配置容器 prometheus 的暴露端口 
# 未配置容器 frpc 的暴露端口 
upstream adminer { server adminer:8080; } 
upstream glances { server glances:61208; } 
upstream gotty { server gotty:8080; } 
upstream homer { server homer:8080; } 

include /etc/nginx/conf.d/80.conf;
