# services:
#   mysql:
#     image: mysql
#     container_name: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=langnang.com
#     # volumes:
#     #   - "./mysql/var/lib/mysql:/var/lib/mysql"
#     #   - "./mysql/etc/mysql:/etc/mysql"
#     # command: mysqld --skip-symbolic-links
#     restart: unless-stopped

#   postgresql:
#     image: postgres:17-alpine
#     container_name: postgresql
#     environment:
#       - POSTGRES_USER=postgresql
#       - POSTGRES_PASSWORD=langnang.com
#       - POSTGRES_DB=postgres
#     ports:
#       - "5432:5432"
#     # volumes:
#     #   - ./postgres/var/lib/postgresql/data:/var/lib/postgresql/data
#     #   - ./postgres/var/log/postgresql:/var/log/postgresql
#     #   - ./postgres/etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
#     #   - ./postgres/etc/postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
#     # command: postgres -c config_file=/etc/postgresql/postgresql.conf
#     restart: unless-stopped

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     # volumes:
#     #   - ./redis/data:/data
#     #   - ./redis/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
#     #   - ./redis/logs:/logs
#     # command: redis-server /usr/local/etc/redis/redis.conf
#     restart: unless-stopped

#   memcached:
#     image: memcached:latest
#     container_name: memcached
#     ports:
#       - "11211:11211"
#     restart: unless-stopped
#   influxdb:
#     image: influxdb:latest
#     container_name: influxdb
#     ports:
#       - "8086:8086"
#     environment:
#       INFLUXDB_DB: influxdb
#       INFLUXDB_ADMIN_USER: influxdb
#       INFLUXDB_ADMIN_PASSWORD: langnang.com
#     # volumes:
#     #   - ./influxdb/var/lib/influxdb2:/var/lib/influxdb2
#     restart: unless-stopped
#   mongodb:
#     image: mongo:4.4
#     container_name: mongodb
#     environment:
#       - TZ=Asia/Shanghai
#       # - MONGO_INITDB_DATABASE=mongodb
#       - MONGO_INITDB_ROOT_USERNAME=mongodb
#       - MONGO_INITDB_ROOT_PASSWORD=langnang.com
#       # MONGO_INITDB_ROOT_USERNAME: username  # mongo username
#       # MONGO_INITDB_ROOT_PASSWORD: password  # mongo password
#     ports:
#       - "27017:27017"
#     # volumes:
#     #   - ./mongodb/data/db:/data/db
#     #   - ./mongodb/data/logs:/data/logs
#     #   - ./mongodb/data/configdb:/data/configdb
#     # command: mongod --config /etc/mongo/mongod.conf
#     restart: unless-stopped
#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     # volumes:
#     #   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"
#     restart: unless-stopped
