# 未配置容器 postgresql 的暴露端口 
# 未配置容器 redis 的暴露端口 
# 未配置容器 memcached 的暴露端口 
# 未配置容器 influxdb 的暴露端口 
# 未配置容器 mongodb 的暴露端口 
# 未配置容器 prometheus 的暴露端口 
upstream homer { server homer:8080; } 
upstream portainer { server portainer-agent:9000; } 
upstream reference { server reference:3000; } 
upstream adminer { server adminer:8080; } 

include /etc/nginx/conf.d/80.conf;
