networks:
  software-network:
    external: true
services:
  composer-laravel8:
  composer-lumen8:
  node-vuepress:
    image: node:alpine
    working_dir: /app/node.vuepress
    ports:
      - 8080
    volumes:
      - ./node.vuepress:/app/node.vuepress
      - node-vuepress_modules:/app/node.vuepress/node_modules
    networks:
      - software-network
    command: sh -c "yarn install && yarn run docs:dev"
  node-vitepress:
    image: node:alpine
    working_dir: /app/node.vitepress
    ports:
      - 5173
    volumes:
      - ./node.vitepress:/app/node.vitepress
      - node-vitepress_modules:/app/node.vitepress/node_modules
    networks:
      - software-network
    command: sh -c "yarn install && yarn run docs:dev"

volumes:
  node-vuepress:
  node-vuepress_modules:
  node-vitepress:
  node-vitepress_modules:
