networks:
  software-network:
    external: true
services:
  composer-latest:
    image: composer:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - composer-latest:/app
      - ./.sh:/app/.sh
    command: sh -c "composer init"
    # restart: unless-stopped
    networks:
      - software-network
  node-latest:
    image: node:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - node-latest:/app
      - ./.sh:/app/.sh
    command: sh -c "node"
    # restart: unless-stopped
    networks:
      - software-network
volumes:
  composer-latest:
  node-latest:
