services:
  frps:
    image: snowdreamtech/frps
    # ports:
    #   - 7000:7000
    #   - 7500:7500
    volumes:
      - ./frps/frps.toml:/etc/frp/frps.toml
    restart: unless-stopped
    network_mode: host
  portainer-agent:
    image: portainer/agent
    ports:
      - 9001:9001
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
