services:
  adminer:
    image: adminer:latest
    # ports:
    #   - 8180:8080
    # volumes:
    #   - ./plugins:/var/www/html/plugins-enabled
    # environment:
    #   - ADMINER_DESIGN=hydra
    #   - ADMINER_PLUGINS=login-ldap
    restart: unless-stopped
  glances:
    image: nicolargo/glances:latest
    environment:
      - TZ=Asia/Shanghai
      - GLANCES_OPT=-w
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 0:61208
    restart: unless-stopped
  gotty:
    image: modenaf360/gotty:latest
    # ports:
    #   - 0:8080
    tty: true
    stdin_open: true
    restart: unless-stopped
  homer:
    image: b4bz/homer:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - ./homer/subs:/www/assets/subs
      - ./homer/config.yml:/www/assets/config.yml
      - ./homer/develop.yml:/www/assets/develop.yml
      - ./homer/custom.css:/www/assets/custom.css
    # ports:
    #   - 0:8080
    restart: unless-stopped
