include:
  - ./docker-compose.database.yml
  - ./docker-compose.host.yml
  - ./docker-compose.proxy.yml
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 8000:8000
      - 9000:9000
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/upstream.d:/etc/nginx/upstream.d
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
