networks:
  software-network:
    external: true
services:
  openclaw:
    image: ghcr.io/getumbrel/openclaw-umbrel:2026.3.1
    container_name: openclaw
    labels:
      yantr.app: "openclaw"
      yantr.service: "AI Assistant"
    init: true
    restart: unless-stopped
    ports:
      - "18789"
      - "18790"
    volumes:
      - openclawdata:/data
      - openclawlinuxbrew:/home/linuxbrew

  # latest:
  #   image: alpine/openclaw
  #   ports:
  #     - "0:3000" # 控制台端口。
  #     - "0:18789" # 服务通信端口。
  #   environment:
  #     - CLAUDE_API_KEY=your_api_key_here # 替换为阿里云百炼 API Key。
  #   volumes:
  #     - latest_data:/app/data
  #   networks:
  #     - software-network
volumes:
  latest_data:
  openclawdata:
  openclawlinuxbrew:
