networks:
  software-network:
    external: true
services:
  ollama:
    image: ollama/ollama
    labels:
      software.app: "ollama"
      software.service: "AI Models"
    ports:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: "0.0.0.0"
    restart: unless-stopped
    networks:
      - software-network
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    labels:
      software.app: "open-webui"
      software.service: "AI UI"
    ports:
      - "8080"
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
    volumes:
      - open-webui_data:/app/backend/data
    restart: unless-stopped
    networks:
      - software-network

volumes:
  ollama_data:
  open-webui_data:
