networks:
  software-network:
    external: true
services:
  mysql:
    image: mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=langnang.com
    volumes:
      - mysql_data:/var/lib/mysql
      #   - "./mysql/etc/mysql:/etc/mysql"
      # command: mysqld --skip-symbolic-links
    restart: unless-stopped
    networks:
      - software-network

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=langnang.com
      - POSTGRES_DB=postgres
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #   - ./postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    #   - ./postgres/var/log/postgresql:/var/log/postgresql
    #   - ./postgres/etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    #   - ./postgres/etc/postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf

    restart: unless-stopped
    networks:
      - software-network

  redis:
    image: redis:latest
    ports:
      - "6379"
    # volumes:
    #   - ./redis/data:/data
    #   - ./redis/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    #   - ./redis/logs:/logs
    # command: redis-server /usr/local/etc/redis/redis.conf

    restart: unless-stopped
    networks:
      - software-network
  memcached:
    image: memcached:latest
    ports:
      - "11211"
    restart: unless-stopped
    networks:
      - software-network

  influxdb:
    image: influxdb:latest
    ports:
      - "8086"
    environment:
      INFLUXDB_DB: influxdb
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: langnang.com
    volumes:
      #   - ./influxdb/var/lib/influxdb2:/var/lib/influxdb2
      - influxdb_etc:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - software-network
  mongodb:
    image: mongo:4.4
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=langnang.com
      # MONGO_INITDB_ROOT_USERNAME: username  # mongo username
      # MONGO_INITDB_ROOT_PASSWORD: password  # mongo password
    ports:
      - "27017"
    volumes:
      - mongodb_db:/data/db
      - mongodb_configdb:/data/configdb
      #   - ./mongodb/data/logs:/data/logs
    # command: mongod --config /etc/mongo/mongod.conf
    restart: unless-stopped
    networks:
      - software-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090"
    volumes:
      # - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - software-network
#
volumes:
  influxdb_etc:
  influxdb_data:
  mysql_data:
  mongodb_db:
  mongodb_configdb:
  postgres_data:
  prometheus_data:
