networks:
  software-network:
    external: true
services:
  latest:
    image: mereith/van-blog
    ports:
      - 80
    environment:
      - TZ=Asia/Shanghai
      - VAN_BLOG_DATABASE_URL=mongodb://root:langnang.com@compose-mongodb-1:27017/mongodb
    volumes:
      - latest_static:/app/static # 图床文件
      - latest_log:/var/log # 日志文件
    restart: unless-stopped
    networks:
      - software-network
volumes:
  latest_static:
  latest_log:
