[common]
# frpc.toml
webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin1234"
# server_addr为FRPS服务器IP地址
server_addr = 101.126.135.139
# server_port为服务端监听端口，bind_port
server_port = 7000
# 身份验证
token = langnang.com


[{{ .Envs.DEVICE_NAME }}::FTP] 
type = tcp
local_ip = host.docker.internal
local_port = 21
remote_port = 21{{.Envs.DEVICE_CODE}}

[{{ .Envs.DEVICE_NAME }}::SSH] 
type = tcp
local_ip = host.docker.internal
local_port = 22
remote_port = 22{{.Envs.DEVICE_CODE}}

[{{ .Envs.DEVICE_NAME }}::RDP]
type = tcp
local_ip = host.docker.internal
local_port = 3389
remote_port = 38{{.Envs.DEVICE_CODE}}

[{{ .Envs.DEVICE_NAME }}::Cpolar]
type = tcp
local_ip = host.docker.internal
local_port = 9200
remote_port = 92{{.Envs.DEVICE_CODE}}

[{{ .Envs.DEVICE_NAME }}::Nginx-80]
type = tcp
local_ip = nginx
local_port = 80
remote_port = 8{{.Envs.DEVICE_CODE}}

[{{ .Envs.DEVICE_NAME }}::DPanel]
type = tcp
local_ip = dpanel
local_port = 8080
remote_port = 80{{  .Envs.DEVICE_CODE  }}

[{{ .Envs.DEVICE_NAME }}::Portainer]
type = tcp
local_ip = portainer-ce
local_port = 9000
remote_port = 90{{  .Envs.DEVICE_CODE  }}

[{{ .Envs.DEVICE_NAME }}::Ollama]
type = tcp
local_ip = ollama
local_port = 11434
remote_port = 143{{  .Envs.DEVICE_CODE  }}

[{{ .Envs.DEVICE_NAME }}::Open-WebUI]
type = tcp
local_ip = open-webui
local_port = 8080
remote_port = 180{{  .Envs.DEVICE_CODE  }}