name: 🚀 Deploy langnang.22web.org on push with FTP

on:
  push:
    branches:
      - master
    paths:
      - "composer/**"

jobs:
  deploy:
    name: 🎉 Deploy to langnang.22web.org
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14.x

      # - name: Install node dependencies
      #   run: cd 200.vue2-ui && yarn install

      # - name: Build pages
      #   run: cd 200.vue2-ui && npm run build

      - name: Install composer dependencies
        run: cd composer && composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b32_28202196
          # ftp password
          password: ${{ secrets.ftp_password }}
          # local dir
          local-dir: ./composer/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /langnang.22web.org/htdocs/
          # File to Exclude
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
            **/illuminate/Account/**
            **/illuminate/Arr/**
            **/illuminate/Artisan/**
            **/illuminate/Auth/**
            **/illuminate/Autoload/**
            **/illuminate/Blade/**
            **/illuminate/Broadcast/**
            **/illuminate/Bus/**
            **/illuminate/Cache/**
            **/illuminate/Collection/**
            **/illuminate/Command/**
            **/illuminate/Console/**
            **/illuminate/Container/**
            **/illuminate/Contract/**
            **/illuminate/Cookie/**
            **/illuminate/Crypt/**
            **/illuminate/Date/**
            **/illuminate/Dump/**
            **/illuminate/Eloquent/**
            **/illuminate/Event/**
            **/illuminate/File/**
            **/illuminate/FileSystem/**
            **/illuminate/Filter/**
            **/illuminate/Gate/**
            **/illuminate/HTML/**
            **/illuminate/Hash/**
            **/illuminate/Http/**
            **/illuminate/Internationalization/**
            **/illuminate/Js/**
            **/illuminate/Log/**
            **/illuminate/Mail/**
            **/illuminate/Migration/**
            **/illuminate/Model/**
            **/illuminate/Notification/**
            **/illuminate/Paginator/**
            **/illuminate/Password/**
            **/illuminate/Pipeline/**
            **/illuminate/Process/**
            **/illuminate/Query/**
            **/illuminate/Queue/**
            **/illuminate/RateLimiter/**
            **/illuminate/Redirect/**
            **/illuminate/Response/**
            **/illuminate/Schedule/**
            **/illuminate/Schema/**
            **/illuminate/Seeder/**
            **/illuminate/Selector/**
            **/illuminate/Session/**
            **/illuminate/Spider/**
            **/illuminate/Storage/**
            **/illuminate/Traitor/**
            **/illuminate/URL/**
            **/illuminate/Usage/**
            **/illuminate/User/**
            **/illuminate/Validator/**
            **/illuminate/Yielder/**
